Step3 - 사다리 (게임 실행)
zuniors/java-ladder pull request #3
Opened 2020-06-09 05:20 UTC by gmlwjd9405

## 기능 요구사항 목록 
### # M (Model)
#### Player
- [x] 이름 정보를 가지고 Player 를 생성할 수 있다.
- [x] 참여자의 이름은 5글자를 넘길 수 없다.
- [x] 논리적 동치성 비교 

#### Players
- [x] , 를 기준으로 Player 를 생성할 수 있다.
- [x] null 이거나 0개의 이름이 입력되면 예외를 반환한다.
- [x] 배열 순서에 해당하는 Player 를 반환할 수 있다.
- [x] Players 의 모든 이름을 반환할 수 있다. 
- [x] Players 수를 반환할 수 있다. 

#### Prize
- [x] 이름 정보를 가지고 Prize 를 생성할 수 있다.
- [x] 사타리 타기 결과값은 5글자를 넘길 수 없다.
- [x] 논리적 동치성 비교 

#### Prizes
- [x] , 를 기준으로 Prize 를 생성할 수 있다.
- [x] null 이거나 0개의 이름이 입력되면 예외를 반환한다.
- [x] 배열 순서에 해당하는 Prize 를 반환할 수 있다.
- [x] Prizes 의 모든 이름을 반환할 수 있다. 
- [x] Prizes 수를 반환할 수 있다. 

#### Height
- [x] 사다리의 높이는 최소 1이상 이어야 한다.
- [x] 1 이상의 값으로 사다리의 높이를 생성할 수 있다. 
- [x] 논리적 동치성 비교 
    
#### Ladder
: 사다리 높이 수 만큼의 RowPillars 로 구성된 사다리 판 

```
List<RowPillars>   Height | Player1 - Player2 - Player3 (3명)
--------------------------+------------------------------
RowPillars1          1    | Pillar1 - Pillar2 - Pillar3 
RowPillars2          2    | Pillar4 - Pillar5 - Pillar6 
```

- [x] 기둥이 하나도 없거나 null 이면 예외를 반환한다.
- [x] (numOfPlayers * height)개의 기둥으로 사다리 판을 생성한다.
- [x] 한 명의 사용자가 사다리를 타면 index 0 의 prize 리스트를 반환한다. 
- [x] 모든 사용자가 사다리를 타고 난 결과에 대한 prize index 리스트를 반환한다.
    - [ ] 원하는 결과값을 미리 지정해서 해당하는 prizes 가 나오는지 확인?

#### RowPillars 
: 한 행에 있는 모든 세로 모양의 기둥들 (|)
- [x] 기둥의 최소 개수는 1 이상 이어야 한다.
- [x] 사이에 놓을 수 있는 계단을 포함할 수 있다.
- [x] 한 행의 모든 계단을 반환할 수 있다.
- [x] 한 행에 포함되어 있는 기둥의 개수 (width) 를 반환할 수 있다.
- [x] 한 행의 position 에 위치한 계단의 상태에 따라 다음 위치를 반환할 수 있다.

#### PillarCount
: 한 행에 있는 사다리 기둥의 개수 = 열의 개수 = (참여자의 수)
- [x] 기둥의 최소 개수는 1 이상 이어야 한다.
- [x] 1 이상의 값으로 사다리 기둥의 개수를 생성할 수 있다.
- [x] 한 행에 있는 사다리 기둥의 개수가 최소 개수인 1과 같으면 return true 를 반환한다.

#### Stairs
: 한 행을 구성하는 계단(가로줄)들 (기둥 사이를 잇는 계단: -----) 
- [x] 기둥의 개수가 null 이면 예외를 반환한다.
- [x] 기둥의 개수 만큼 수평을 따라 계단을 만들 수 있다.
- [x] 기둥의 최소 개수인 1보다 작은 수로 계단을 만들 수 없다.
- [x] 기둥의 개수가 1개면 계단 없이 하나의 기둥으로만 구성된다.
- [x] index 위치 계단의 상태에 따라 다음 위치를 반환한다. 

#### Stair
: 기둥 사이를 잇는 계단 
- [x] 계단이 존재하는 기둥의 위치와 계단이 있는지에 대한 상태값으로 계단을 생성한다.
- [x] 계단의 상태값이 null 이면 예외를 반환한다.
- [x] 첫 번째 기둥의 계단은 랜던 전략으로 생성한다.
- [x] 중간 기둥의 계단은 앞에 계단이 있으면 계단을 생성하지 않는다.
- [x] 중간 기둥의 계단은 랜덤 전략으로 생성한다.
- [x] 마지막 기둥의 계단은 계단을 둘 수 없다.
- [x] 계단의 상태값(계단이 있는지 없는지)을 가져올 수 있다.
- [x] 해당 기둥의 계단의 상태에 따라 다음 위치를 반환할 수 있다. 

#### StairState / State
: 계단이 있는지 없는지에 대한 상태값 
- [x] 처음 ~ 중간 기둥의 계단은 생성 전략에 따라 계단을 둔다.
- [x] 마지막 기둥의 계단 또는 앞에 이미 계단이 있는 중간 기둥의 계단은 계단을 두지 않는다.
- [x] 오른쪽에 계단이 있으면 return true 
- [x] 해당 기둥의 계단의 상태에 따라 다음 위치를 반환한다.
- [x] 논리적 동치성 비교 

#### StairGenerationStrategy
: 좌표의 계단을 생성하는 함수형 인터페이스 

#### RandomStairGenerationStrategy
: 랜덤으로 좌표의 계단을 생성하는 구체적인 전략
- [x] true 또는 false 를 반환한다.

#### LadderGame
: 게임 참여자와 최대 사다리 높이의 개수로 사다리 판을 구성
- [x] 게임 참여자 이름과 사다리 판의 정보를 가진 LadderShapeResult 를 반환할 수 있다.
- [x] 게임 참여자와 사다리 높이의 개수로 LadderGame 을 생성할 수 있다.
- [x] 게임 참여자가 null 이면 예외가 발생한다.
- [x] 게임 실행 결과가 null 이면 예외가 발생한다.
- [x] 사다리 높이가 null 이면 예외가 발생한다.
- [x] 게임 참여자의 수와 게임 실행 결과의 수가 맞지 않으면 예외가 발생한다. 
- [x] 게임 참여자가 1명일 때 LadderGame 을 play 할 수 있다.
- [x] 게임 참여자가 1명이고 사다리의 높이가 N이면, N개의 Pillar 를 출력한다.
    - [ ] 테스트 코드 추가 
- [x] 게임을 수행하고 난 후 참여자의 모든 이름을 반환한다.
- [x] 게임 참여자가 1명 일 때, match 되는 prize 하나를 반환한다.
- [ ] 게임 참여자가 여러 명일 때, 임의로 결과값을 정해서 match 되는 값이 맞는지 확인?

#### LadderShapeResult
: 사다리 판 출력을 위한 실행 결과 정보
- [x] 참여자의 이름 리스트와 계단 라인 정보, 게임 실행 결과 이름 리스트로 LadderShapeResult 를 생성할 수 있다. 
- [x] 참여자의 이름을 반환할 수 있다.
- [x] 실행 결과 이름을 반환할 수 있다.

#### LadderMatchResult
: 사다리 게임의 게임 결과 출력을 위한 정보
- [x] 게임 결과가 null 이면 예외를 반환한다.
- [x] 결과를 알고자 하는 참여자의 이름이 참여자에 포함되지 않은 경우 예외를 반환한다.
- [x] 게임 참여자 리스트를 반환할 수 있다.  
- [x] 참여자의 이름에 해당하는 참여자의 게임 결과값을 반환한다. 

#### StairDto
: 각 행의 좌->우로 가면서 계단 라인을 그리기 위한 값 
- [x] 사다리의 계단 라인이 null 이거나 라인이 하나도 없으면 예외를 반환한다.
- [x] Ladder 의 각 행의 좌->우로 가면서 Stair 의 existLine 정보를 이용하여 출력하기 쉬운 boolean 리스트 값으로 변환한다. 
- [x] 각 행의 계단 라인인 List<Boolean> 을 반환한다.
    - [ ] 테스트 코드 추가 (미리 입력된 값에 따라 상태에 따라 예상하는 StairDto 확인?)
- [x] 계단 라인의 수가 0개 인지(해당 행은 하나의 기둥으로 구성) 확인할 수 있다.

#### LadderShapeInfo
: 사다리 모양을 정하기 위한 입력 정보
- [x] 게임 참여자가 null 이면 예외가 발생한다.
- [x] 사다리 높이가 null 이면 예외가 발생한다.
- [x] 게임 실행 결과가 null 이면 예외가 발생한다. 
- [x] 입력한 게임 참여자를 반환한다.
- [x] 입력한 사다리의 높이를 반환한다.
- [x] 입력한 게임 실행 결과를 반환한다. 
- [x] 게임 참여자 수를 바탕으로 사다리의 한 행에 있는 기둥의 수를 반환한다. 
- [x] 게임 참여자의 수와 게임 실행 결과의 수가 맞지 않으면 예외가 발생한다. 

### # V (View)
#### InputView
- [x] 참여자의 이름을 쉼표로 구분하여 문자열로 입력받는다. 
- [x] 최대 사다리 높이의 개수를 입력받는다.
- [x] 사다리 타기의 실행 결과를 입력받는다.
- [x] 결과를 보고 싶은 사람을 입력받는다. 

#### ResultView
- [x] 참여자의 이름을 출력한다.
- [x] 생성한 사다리 게임판을 출력한다. 
- [x] 사다리 타기의 실행 결과를 출력한다. 
- [x] 결과를 보고 싶은 사람에 대한 사다리 게임 결과를 출력한다.

2020-06-09 05:20 UTC, gmlwjd9405 commented
이번 step 이 생각보다 어렵고 오래 걸린 것 같습니다.. 😭 

그리고 테스트 코드도 아직 제대로 구현하지 못한 부분이 있어서 조언 부탁드립니다.
기능 요구 사항으로 정리한 체크 리스트 중 표시하지 않는 내용에 대해 아래의 질문 남깁니다. 
감사합니다!! 😄 

1. 해당 테스트 코드가 필요한지 
2. 임의로 결과를 조작해서 테스트를 하려면 어떻게 하는 것이 좋을지

2020-06-09 07:35 UTC, nokchax requested changes
커밋수를 보니 얼마나 힘들었을지 눈에 보이네요 😲😲
코드 구성도 아주 좋았고, 테스트도 꼼꼼히 잘 작성하셨어요!
다만 아쉬웠던 점이 있다면 너비가 1인경우 표현으로 인해서 여러 분기 점이 생긴것!
이것만 해결하면 더 읽기 좋은 코드가 될것 같습니다.

고생했어요! 😄😄😄👍💯

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/LadderGame.java
> +        this.ladder = Ladder.of(ladderShapeInfo);
사다리와 player, prize를 잘 나눠두셨습니다 👍

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/dto/LadderMatchResult.java
> +        return matchResult.get(player);
equals를 잘 이용하셨네요 👍

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/dto/LadderShapeResult.java
> +    private LadderShapeResult(final List<String> playerNames, final List<String> prizeNames, final List<StairDto> stairDtos) {
`규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.`
파라미터도 마찬가지예요!
player와 prize를 묶어보는건 어떨까요?

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/dto/StairDto.java
> +    }
아래에 상세히 써두긴 하겠지만 삭제되었으면 하는 로직!

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/ladder/Height.java
> +    }
💯

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/ladder/Ladder.java
> +            return Collections.singletonList(FIRST_INDEX);
코드 전체적으로 너비가 1인 경우 Stair의 사이즈가 0으로 표현하면서 여러 분기 로직이 추가된거 같아요
single player일 때에도 하나의 pillar가 생성되도록 만들면 어떨까요? State가 empty인 Stair하나면 될거같은데 🤔 
그러면 로직이 통일되어서 더 깔끔해 질거 같습니다!

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/ladder/Ladder.java
> +        return position;
```suggestion
        return rowPillars.stream()
                .reduce(playerPosition, (byPosition, rowPillar) -> rowPillar.move(byPosition),
                        (x, y) -> {throw new RuntimeException("Can't reduce in parallel environment");});
```
이런식으로 reduce를 사용할 수 있어요! 세번째 파라미터는 병렬처리를 막기위해서 예외를 던지도록 했습니다.

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/ladder/Stair.java
> +    public boolean isExistLine() {
`isRightLineExist()`는 어떨까요? 좀 더 명확한 표현이 될거 같아요

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/ladder/Stairs.java
> +        }
여기도 너비가 1일때를 0개의 Stair로 표현하려고 발생하는 분기!

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/ladder/Stairs.java
> +        stairs.add(currentStair.createOfLastPillar());
initFirst(), initMiddle(), initLast() 처럼 나눠보는건 어떨까요?

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/ladder/State.java
> +    LEFT(position -> position - 1);
GOOOOOD 👍👍👍💯

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/ladder/State.java
> +    }
ofNextPillar(() -> false) 를 호출하는 것으로 대체할수 있을거 같아요!

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/ladder/State.java
> +    public boolean isExistLine() {
isRightLineExist() 로 명확하게

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/ladder/shape/LadderShapeInfo.java
> +    private final Height height;
위에 써뒀지만 인스턴스 변수를 줄여봅시다!

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/ladder/shape/LadderShapeInfo.java
> +        }
이거는 그냥 넘어가도 될거 같은데 저는 아래같은 유틸 클래스를 만들어서 처리했어요 참고용으로만! 봐주세요
```java
public class ObjectUtil {
    private static final String DEFAULT_NULL_EXCEPTION_MESSAGE = "Some parameter is null";

    private ObjectUtil() {}

    @SafeVarargs
    public static <T> void checkNull(final T... parameters) {
        checkNull(DEFAULT_NULL_EXCEPTION_MESSAGE, parameters);
    }

    public static <T> void checkNull(final T parameters, final String exceptionMsg) {
        if (parameters == null) {
            throw new IllegalArgumentException(exceptionMsg);
        }
    }

    @SafeVarargs
    public static <T> void checkNull(final String exceptionMsg, final T... parameters) {
        Arrays.stream(parameters)
                .filter(Objects::isNull)
                .findAny()
                .ifPresent(parameter -> {
                    throw new IllegalArgumentException(exceptionMsg);
                });
    }
}
```

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/ladder/strategy/RandomStairGenerationStrategy.java
> +    }
Singleton 👍👍👍

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/player/Players.java
> +        if (Objects.isNull(names) || names.size() < 1) {
요건 그냥 StringUtil쓰는게 낫지 않을까요?

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/domain/prize/Prizes.java
> +        if (Objects.isNull(names) || names.size() < 1) {
여기도 StringUtil.isEmpty()

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/view/ResultView.java
> +        }
여기도 너비 1을 0개의 Stair로 표현했기 때문에 발생하는 분기

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/view/ResultView.java
> +        printPrizeMatchResult(ladderMatchResult.match(targetPlayerNames));
```suggestion
        System.out.print(MATCH_RESULT_MESSAGE);
        System.out.println();
        
        if (targetPlayerNames.equalsIgnoreCase(ALL_PLAYERS)) {
            ladderMatchResult.getPlayers()
                    .forEach(player -> printPlayerAndPrizeMatchResult(player, ladderMatchResult.match(player.getName())));
            return;
        }
        
        printPrizeMatchResult(ladderMatchResult.match(targetPlayerNames));
```

2020-06-09 07:35 UTC, nokchax commented on src/main/java/ladder/view/ResultView.java
> +    public static void printResult(final LadderMatchResult ladderMatchResult, final String targetPlayerNames) {
```suggestion
    public static void printResult(final LadderMatchResult ladderMatchResult, final String targetPlayerName) {
```

2020-06-09 07:35 UTC, nokchax commented on src/test/java/ladder/domain/player/PlayersTest.java
> +        names.add("honux");
```suggestion
        names = Arrays.asList("pobi", "honux");
```
넘어가려다가 깜빡하신거 같아서?

2020-06-09 07:35 UTC, nokchax commented on contents/step3.md
> +- 사다리 게임에 참여하는 사람에 이름을 최대5글자까지 부여할 수 있다. 사다리를 출력할 때 사람 이름도 같이 출력한다.
테스트 못한 이유는 말씀 드렸듯이 테스트 환경을 조성할 수 있는 전략 패턴이 안쪽에 숨겨져 있기 때문이에요,
전략패턴 또한 초기화에 사용되는 개념이기 때문에 사다리 밖으로 빼낸다면, 요구사항에 써두셨지만 아직 구현하지 못한 여러 테스트를 작성할 수 있을겁니다 :)

2020-06-09 07:45 UTC, nokchax commented on src/main/java/ladder/domain/player/Players.java
> +        if (Objects.isNull(names) || names.size() < 1) {
아 리스트네?
```suggestion
        if (Objects.isNull(names) || names.isEmpty()) {
```

2020-06-09 07:45 UTC, nokchax commented on src/main/java/ladder/domain/prize/Prizes.java
> +        if (Objects.isNull(names) || names.size() < 1) {
```suggestion
        if (Objects.isNull(names) || names.isEmpty()) {
```
😅😅😅

2020-06-09 09:24 UTC, gmlwjd9405 commented on src/test/java/ladder/domain/player/PlayersTest.java
> +        names.add("honux");
ㅎㅎㅎ.... 다 고쳐놔야지...

2020-06-09 09:50 UTC, gmlwjd9405 commented on src/main/java/ladder/domain/ladder/Ladder.java
> +        return position;
https://www.baeldung.com/java-stream-reduce
https://www.baeldung.com/java-stream-sum

2020-06-09 11:00 UTC, gmlwjd9405 commented on src/main/java/ladder/domain/ladder/shape/LadderShapeInfo.java
> +        }
https://www.baeldung.com/java-safevarargs
`@SafeVarargs`:  제너릭 같은 가변인자 매개변수를 사용할 때 경고를 무시

2020-06-09 11:06 UTC, gmlwjd9405 commented on src/main/java/ladder/domain/ladder/Stairs.java
> +        stairs.add(currentStair.createOfLastPillar());
https://github.com/next-step/java-ladder/pull/403#discussion_r434902650

해당 리뷰를 받고 불필요한 메서드 분리를 하나로 통합했는데, 
이건 개인의 코딩 스타일인 거 같아서 고민해보고 피드백 반영하도록 하겠습니다! :) 👍

2020-06-09 11:47 UTC, gmlwjd9405 commented on src/main/java/ladder/domain/ladder/Stairs.java
> +        }
이 부분은 참여자가 1명일 때, State 가 EMPTY인 Stair 을 할당해야 하는 부분이기 때문에 제거가 불가능할 거 같습니다!

```java
    private static List<Stair> createHorizontalStairs(final PillarCount pillarCount) {
        if (pillarCount.isMinCount()) {
            return Collections.singletonList(Stair.of(StairState.EMPTY));
        }

        List<Stair> stairs = new ArrayList<>();
        int middlePillarCount = pillarCount.getValue() - FIRST_AND_LAST_PILLAR_COUNT;

        Stair currentStair = Stair.createOfFirstPillar();
        stairs.add(currentStair);
        for (int i = 0; i < middlePillarCount; i++) {
            currentStair = currentStair.createOfNextPillar();
            stairs.add(currentStair);
        }
        stairs.add(currentStair.createOfLastPillar());

        return stairs;
    }
```

더 단순하게 구조화할 수 있는 좋은 방법이 있을까요? ❓ 🤔

2020-06-09 12:08 UTC, nokchax commented on src/main/java/ladder/domain/ladder/Stairs.java
> +        }
아하 그렇군 이런 경우는 구조를 그대로 두면 삭제하기 힘들고... 음... 말로 풀어서 설명가기 구찮으므로..

```java
// 사다리 한단
public class Step {
    private static final int MINIMUM_LADDER_WIDTH = 1;

    private final List<Column> columns;

    private Step(final LadderInitInfo ladderInitInfo) {
        validate(ladderInitInfo);

        columns = new ArrayList<>(ladderInitInfo.getLadderWidth());
        createFirst(ladderInitInfo);
        createMid(ladderInitInfo);
        createLast(ladderInitInfo);
    }

    private void createFirst(final LadderInitInfo ladderInitInfo) {
        if (ladderInitInfo.getLadderWidth() == MINIMUM_LADDER_WIDTH) {
            columns.add(Column.init(() -> false));
            return;
        }

        columns.add(Column.init(ladderInitInfo.getLadderInitStrategies()));
    }

    private void createMid(final LadderInitInfo ladderInitInfo) {
        if(ladderInitInfo.getLadderWidth() < MINIMUM_LADDER_WIDTH + 1) {
            return;
        }

        Stream.generate(() -> createNextColumn(ladderInitInfo.getLadderInitStrategies()))
                .limit(ladderInitInfo.getLadderWidth() - 2) //add except first and last column
                .forEach(columns::add);
    }

    private void createLast(final LadderInitInfo ladderInitInfo) {
        if (ladderInitInfo.getLadderWidth() > MINIMUM_LADDER_WIDTH) {
            columns.add(createLastColumn());
        }
    }
... 
```
제가 짰던 코드로 대신해봐요
[Tell, don't ask](https://effectiveprogramming.tistory.com/entry/Tell-dont-ask) 에 입각해서 폭에 관계없이 첫 pillar 과 중간 pillars 그리고 마지막 pillar 생성 요청을 보내고 각 함수 내부에서는 폭에 따라 판단하여 추가하거나 무시하는 식으로 해봤어요. 꼭 정답은 아니고 참고만 해보세요!

2020-06-09 12:19 UTC, nokchax commented on src/main/java/ladder/domain/ladder/Stairs.java
> +        }
생각해보니까 사실 이 코멘트는 그냥 무시해도 되겠네요 ㅋㅋ... 저도 최소 값과 비교해서 분기를 태워놔서

2020-06-09 15:52 UTC, gmlwjd9405 commented on src/main/java/ladder/domain/ladder/Ladder.java
> +        return position;
구현한 사다리 타기 게임에서 각 행(RowPillars) 사이에는 순서 보장이 필요한 구조
- 스트림의 경우 순서에 상관 없이 병렬 처리가 가능
- 세번 째 파라미터는 병렬 처리 결과 간의 값들을 어떻게 처리할지에 대한 방법 정의
- 병렬 처리로 수행하는 경우, 예외 발생 (stream 대신 parallelStream 을 사용하는 경우)

2020-06-11 04:04 UTC, nokchax approved these changes
리뷰 적용은 다음 스텝에서 😃

2020-06-11 04:04 UTC, merged